### ISSUE TITLE
Rng_handle in mqtt test undefined

### ISSUE THREAD

**Issue by ignatiuscrean** [al3xsh/embedded-computer-networks#1]
i think the rng_handle is undefined.
![image](https://user-images.githubusercontent.com/43886771/101408405-42cebf80-38d4-11eb-8890-a6d878bfe9ba.png)

I tried to defined it but got no seeding of the random number generator.
![image](https://user-images.githubusercontent.com/43886771/101408767-cab4c980-38d4-11eb-9add-ce877a7549cc.png)

**Comment by al3xsh** [comment]
Are you using the latest version of the libraries? Specifically the random number library - as described in:

https://github.com/al3xsh/embedded-computer-networks/commit/e2d94c17062a8284ab8c47a719c4fa2b8e85fdba

I had to update the library to expose the rng_handle so it could be used for hardware entropy generation (see page 8 of the lab sheet for discussion about the importance of entropy).

**Comment by ignatiuscrean** [comment]
I needed to update the libraries.

cheers
